spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/todolist
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

